name: cls_notebooks
channels:
  - defaults
dependencies:
  - astroid=2.11.7
  - black=22.6.0
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - cffi=1.15.1
  - cfgv=3.3.1
  - click=8.0.4
  - dill=0.3.6
  - distlib=0.3.2
  - filelock=3.6.0
  - flit-core=3.6.0
  - identify=2.5.5
  - isort=5.9.3
  - lazy-object-proxy=1.6.0
  - libcxx=14.0.6
  - libffi=3.4.2
  - mccabe=0.7.0
  - mypy_extensions=0.4.3
  - ncurses=6.3
  - nodeenv=1.7.0
  - openssl=1.1.1s
  - pathspec=0.9.0
  - pip=22.3.1
  - platformdirs=2.5.2
  - pre-commit=2.20.0
  - pycparser=2.21
  - pydocstyle=6.1.1
  - pylint=2.14.5
  - python=3.9.15
  - pyyaml=6.0
  - readline=8.2
  - setuptools=65.5.0
  - shellcheck=0.7.2
  - snowballstemmer=2.2.0
  - sqlite=3.40.0
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - ukkonen=1.0.1
  - virtualenv=20.16.2
  - wheel=0.37.1
  - wrapt=1.14.1
  - xz=5.2.8
  - yaml=0.2.5
  - zlib=1.2.13
