name: edu-nb
channels:
  - defaults
dependencies:
  - appnope=0.1.2
  - astroid=2.11.7
  - asttokens=2.0.5
  - backcall=0.2.0
  - black=22.6.0
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - ca-certificates=2022.10.11
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfgv=3.3.1
  - click=8.0.4
  - contourpy=1.0.5
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - dill=0.3.6
  - distlib=0.3.2
  - entrypoints=0.4
  - executing=0.8.3
  - filelock=3.6.0
  - flit-core=3.6.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - identify=2.5.5
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=8.7.0
  - isort=5.9.3
  - jedi=0.18.1
  - jpeg=9e
  - jupyter_client=7.4.7
  - jupyter_core=4.11.2
  - kiwisolver=1.4.2
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=14.0.6
  - libdeflate=1.8
  - libffi=3.4.2
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.4.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nodeenv=1.7.0
  - numpy=1.23.4
  - numpy-base=1.23.4
  - openssl=1.1.1s
  - packaging=21.3
  - parso=0.8.3
  - pathspec=0.9.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.3.1
  - platformdirs=2.5.2
  - pre-commit=2.20.0
  - prompt-toolkit=3.0.20
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pydocstyle=6.1.1
  - pygments=2.11.2
  - pylint=2.14.5
  - pyparsing=3.0.9
  - python=3.9.15
  - python-dateutil=2.8.2
  - pyyaml=6.0
  - pyzmq=23.2.0
  - readline=8.2
  - setuptools=65.5.0
  - shellcheck=0.7.2
  - six=1.16.0
  - snowballstemmer=2.2.0
  - sqlite=3.40.0
  - stack_data=0.2.0
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.1
  - tornado=6.2
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - ukkonen=1.0.1
  - virtualenv=20.16.2
  - wcwidth=0.2.5
  - wheel=0.37.1
  - wrapt=1.14.1
  - xz=5.2.8
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.2
